export const GET_EMPLOYEES_REQUEST = 'EMPLOYEES/GET_EMPLOYEES_REQUEST'
export const GET_EMPLOYEES_SUCCESS = 'EMPLOYEES/GET_EMPLOYEES_SUCCESS'
export const GET_EMPLOYEES_ERROR = 'EMPLOYEES/GET_EMPLOYEES_ERROR'

export const ADD_EMPLOYEES_IDS_REQUEST = 'EMPLOYEES/ADD_EMPLOYEES_IDS_REQUEST'
export const ADD_EMPLOYEES_IDS_SUCCESS = 'EMPLOYEES/ADD_EMPLOYEES_IDS_SUCCESS'
export const ADD_EMPLOYEES_IDS_ERROR = 'EMPLOYEES/ADD_EMPLOYEES_IDS_ERROR'

export const DELETE_EMPLOYEES_IDS_REQUEST = 'EMPLOYEES/DELETE_EMPLOYEES_IDS_REQUEST'
export const DELETE_EMPLOYEES_IDS_SUCCESS = 'EMPLOYEES/DELETE_EMPLOYEES_IDS_SUCCESS'
export const DELETE_EMPLOYEES_IDS_ERROR = 'EMPLOYEES/DELETE_EMPLOYEES_IDS_ERROR'

export const moduleName = 'employees'